#!/bin/bash

# MAIN Report index file
MAIN_RPT="report_index.html"

#FILEOBJ is the current file or directory being reviewed
#RESULTS - function output
RESULTS=""
#********************************************************************************************************************
#********************************************************************************************************************

function HTMLHEADER() {

FILE_OBJ="$1"
#    echo "$FILE_OBJ"
    echo "<html><header>" >> "$FILE_OBJ"
    echo "</header><body>" >>  "$FILE_OBJ"
    echo "<hr>" >>  "$FILE_OBJ"
}

function HTMLFOOTER() {
    echo "--------------------------------------------------------------------------------------------" >> "$FILE_OBJ"
    echo "</body></html>" >>  "$FILE_OBJ"
}


echo "<h3><b>Directory and Subdirectories of The Report dir</b> </h3>" >> "$MAIN_RPT"
        echo "--------------------------------------------------------------------------------------------<p>" >> "$MAIN_RPT"
        
for object in *

do
	
	
	if [ -d "$object" ]
	then 
	
	dirlink="./$object.html" 
#	
        HTMLHEADER "$dirlink"

	echo "<a href=\"$dirlink\">Directory: $object</a> <p>" >> "$MAIN_RPT"
	fi

	
	if [ -f "$object" ]
	then 
        
		echo " <P> File: $object <br>" >> $dirlink
		echo "============================================================================================<br>" >> $dirlink	
                        echo "<pre>" >> $dirlink
                        stat "$object" >> "$dirlink"     # note overwrite contents of previous file
                        echo "</pre>" >> $dirlink
                        echo "<br>" >> "$dirlink"
			echo "Md5sum  :" $(md5sum "$object") "<br>" >> "$dirlink"
			echo "Sha1sum :" $(sha1sum "$object") "<br>" >> "$dirlink"
		echo "============================================================================================<br>" >> $dirlink
		
        file "$object" > typ_object.txt
    
    
            if grep -q JPEG typ_object.txt
            then
            echo "  File: $object is a Graphic file"
                #cp $object ./image_dir
                outputfile="./image_dir/tn_$object"
                
                convert $object -resize 200x200 "$outputfile"
            echo "<img src=\"$outputfile\" height=\"200\" width=\"200\"><p>" >> image_file.html
            else 
            echo "  File: $object"
                    
            fi
        fi
            	
		
            
#           if [ type $object | grep -p jpeg\|JFIF\jpe ]
#		then
#		echo "<img src="\$object\"> " >>  $dirlink	
#                echo "GRAPHIC FILE"
		
#            fi
                echo "" >> $dirlink
                count=$((count+1))
#	fi
HTMLFOOTER "$dirlink"
	

done
	rm -f typ_object.txt
