#!/bin/bash

mkdir image_dir


for object in *

do
	
	
	if [ -f "$object" ]
	then 

            file "$object" > typ_object.txt    
            if grep -q JPEG typ_object.txt
            then
            echo "  File: $object is a Graphic file"
                #cp $object ./image_dir
                outputfile="./image_dir/tn_$object"
                
                convert $object -resize 200x200 "$outputfile"
            echo "<img src=\"$outputfile\" height=\"200\" width=\"200\"><p>" >> image_file.html
            else 
            echo "  File: $object"
                    
            fi
        fi
            

done
rm -f typ_object.txt


